version: "3.9"
services:
  api:
    build: ./NewsLy.Api
    ports:
      - "5000:5000"
    depends_on:
      - mssqldb
  mssqldb:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "<password>"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"