apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsly-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newsly
  template:
    metadata:
      labels:
        app: newsly
    spec:
      containers:
        - name: newsly
          image: philippmoser/newsly:latest
---
apiVersion: v1
kind: Service
metadata:
  name: newsly-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: newsly
  ports:
    - name: newsly
      protocol: TCP
      port: 80
      targetPort: 80